import type { Branch, BusinessInfo, Category, ContactConfig, Product } from './types';
import type { ContentStore } from './adapter';

const PLACEHOLDER_NOTE = 'Placeholder data — verify before public release';

export const seedCategories: Category[] = [
  {
    name: 'Smartphones',
    slug: 'smartphones',
    description: 'Browse our selection of smartphones from leading brands.',
    image: '/images/categories/smartphones.jpg',
    displayOrder: 1,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Laptops',
    slug: 'laptops',
    description: 'Laptops for work, study, and everyday use.',
    image: '/images/categories/laptops.jpg',
    displayOrder: 2,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Tablets',
    slug: 'tablets',
    description: 'Tablets for entertainment, reading, and productivity.',
    image: '/images/categories/tablets.jpg',
    displayOrder: 3,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Phone cases, chargers, earphones, and other accessories.',
    image: '/images/categories/accessories.jpg',
    displayOrder: 4,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Draft Category',
    slug: 'draft-category',
    description: 'This category is not yet published.',
    image: '/images/categories/draft.jpg',
    displayOrder: 5,
    published: 'draft',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
];

export const seedProducts: Product[] = [
  {
    name: 'Samsung Galaxy A56',
    slug: 'samsung-galaxy-a56',
    category: 'smartphones',
    brand: 'Samsung',
    shortDescription: 'A reliable mid-range smartphone with a vibrant display.',
    description:
      'The Samsung Galaxy A56 offers a 6.6-inch Super AMOLED display, 50MP camera, and all-day battery life. A solid choice for everyday use.',
    images: [
      '/images/products/samsung-galaxy-a56-1.jpg',
      '/images/products/samsung-galaxy-a56-2.jpg',
    ],
    specifications: {
      Display: '6.6" Super AMOLED',
      'Rear Camera': '50MP + 8MP + 5MP',
      'Front Camera': '12MP',
      Storage: '128GB',
      RAM: '6GB',
      Battery: '5000mAh',
      'Operating System': 'Android 15',
    },
    priceLabel: 'GHS 2,500',
    featured: true,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Samsung Galaxy A16',
    slug: 'samsung-galaxy-a16',
    category: 'smartphones',
    brand: 'Samsung',
    shortDescription: 'An affordable smartphone with essential features.',
    description:
      'The Samsung Galaxy A16 features a 6.7-inch display, triple camera system, and a long-lasting 5000mAh battery for dependable daily performance.',
    images: ['/images/products/samsung-galaxy-a16-1.jpg'],
    specifications: {
      Display: '6.7" LCD',
      'Rear Camera': '50MP + 5MP + 2MP',
      'Front Camera': '8MP',
      Storage: '64GB',
      RAM: '4GB',
      Battery: '5000mAh',
      'Operating System': 'Android 14',
    },
    priceLabel: 'GHS 1,200',
    featured: false,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'iPhone 16',
    slug: 'iphone-16',
    category: 'smartphones',
    brand: 'Apple',
    shortDescription: 'The latest iPhone with advanced performance and camera.',
    description:
      'iPhone 16 brings the A18 chip, a 48MP camera system, and a bright Super Retina XDR display in a durable design.',
    images: [
      '/images/products/iphone-16-1.jpg',
      '/images/products/iphone-16-2.jpg',
    ],
    specifications: {
      Display: '6.1" Super Retina XDR',
      'Rear Camera': '48MP + 12MP',
      'Front Camera': '12MP',
      Storage: '128GB',
      Chip: 'A18',
      Battery: 'Up to 22 hours video',
      'Operating System': 'iOS 18',
    },
    priceLabel: 'GHS 5,800',
    featured: true,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'HP 250 G10',
    slug: 'hp-250-g10',
    category: 'laptops',
    brand: 'HP',
    shortDescription: 'A practical laptop for office and study tasks.',
    description:
      'The HP 250 G10 pairs a 15.6-inch display with an Intel processor, providing dependable performance for everyday computing.',
    images: ['/images/products/hp-250-g10-1.jpg'],
    specifications: {
      Display: '15.6" HD',
      Processor: 'Intel Core i5-1335U',
      RAM: '8GB',
      Storage: '256GB SSD',
      'Operating System': 'Windows 11',
    },
    priceLabel: 'GHS 3,800',
    featured: true,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Lenovo IdeaPad Slim 3',
    slug: 'lenovo-ideapad-slim-3',
    category: 'laptops',
    brand: 'Lenovo',
    shortDescription: 'A slim and lightweight laptop for everyday productivity.',
    description:
      'Lenovo IdeaPad Slim 3 offers a 14-inch display, fast SSD storage, and a compact form factor for users who need portability.',
    images: ['/images/products/lenovo-ideapad-slim-3-1.jpg'],
    specifications: {
      Display: '14" FHD',
      Processor: 'Intel Core i3-1315U',
      RAM: '8GB',
      Storage: '512GB SSD',
      'Operating System': 'Windows 11 Home',
    },
    priceLabel: 'GHS 3,200',
    featured: false,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Samsung Galaxy Tab A9',
    slug: 'samsung-galaxy-tab-a9',
    category: 'tablets',
    brand: 'Samsung',
    shortDescription: 'A compact tablet for entertainment and light productivity.',
    description:
      'The Samsung Galaxy Tab A9 features an 8.7-inch display, long battery life, and a portable design for reading, streaming, and browsing.',
    images: ['/images/products/samsung-galaxy-tab-a9-1.jpg'],
    specifications: {
      Display: '8.7" TFT',
      Storage: '64GB',
      RAM: '4GB',
      Battery: '5100mAh',
      'Operating System': 'Android 13',
    },
    priceLabel: 'GHS 1,100',
    featured: false,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Apple iPad 10th Gen',
    slug: 'apple-ipad-10th-gen',
    category: 'tablets',
    brand: 'Apple',
    shortDescription: 'A versatile iPad for creativity and everyday use.',
    description:
      'iPad 10th generation features a 10.9-inch Liquid Retina display, A14 Bionic chip, and support for Apple Pencil.',
    images: [
      '/images/products/apple-ipad-10th-gen-1.jpg',
      '/images/products/apple-ipad-10th-gen-2.jpg',
    ],
    specifications: {
      Display: '10.9" Liquid Retina',
      Chip: 'A14 Bionic',
      Storage: '64GB',
      'Front Camera': '12MP Ultra Wide',
      'Operating System': 'iPadOS 17',
    },
    priceLabel: 'GHS 3,500',
    featured: true,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Anker PowerCore 20000',
    slug: 'anker-powercore-20000',
    category: 'accessories',
    brand: 'Anker',
    shortDescription: 'A high-capacity portable charger for multiple charges.',
    description:
      'The Anker PowerCore 20000 provides two USB ports and fast charging support, capable of charging a smartphone multiple times.',
    images: ['/images/products/anker-powercore-20000-1.jpg'],
    specifications: {
      Capacity: '20000mAh',
      'Output Ports': '2x USB-A',
      'Fast Charging': 'Yes',
      Weight: '356g',
    },
    priceLabel: 'GHS 450',
    featured: false,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Samsung Galaxy Buds FE',
    slug: 'samsung-galaxy-buds-fe',
    category: 'accessories',
    brand: 'Samsung',
    shortDescription: 'Wireless earbuds with active noise cancellation.',
    description:
      'Galaxy Buds FE deliver clear sound, active noise cancellation, and a comfortable fit for all-day listening.',
    images: ['/images/products/samsung-galaxy-buds-fe-1.jpg'],
    specifications: {
      Type: 'True Wireless',
      'Noise Cancellation': 'ANC',
      'Battery Life': '6h (buds) / 21h (case)',
      Connectivity: 'Bluetooth 5.2',
    },
    priceLabel: 'GHS 600',
    featured: false,
    published: 'published',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
  {
    name: 'Draft Product Example',
    slug: 'draft-product-example',
    category: 'smartphones',
    brand: 'DemoBrand',
    shortDescription: 'This product is in draft and not publicly visible.',
    description: 'A placeholder product to verify draft filtering works correctly.',
    images: ['/images/products/draft-1.jpg'],
    specifications: {},
    featured: false,
    published: 'draft',
    verificationStatus: 'demo',
    verificationNote: PLACEHOLDER_NOTE,
  },
];

export const seedBranches: Branch[] = [
  {
    name: 'Accra — Osu',
    generalLocation: 'Oxford Street, Osu, Accra',
    phone: '+233XXXXXXXXX',
    whatsapp: '+233XXXXXXXXX',
    openingHours: 'Mon–Sat 09:00–18:00',
    mapUrl: '',
    verificationStatus: 'placeholder',
    verificationNote: 'Replace with verified branch address, phone, and map URL',
  },
  {
    name: 'Kumasi — Adum',
    generalLocation: 'Adum, Kumasi',
    phone: '+233XXXXXXXXX',
    whatsapp: '+233XXXXXXXXX',
    openingHours: 'Mon–Sat 09:00–17:30',
    mapUrl: '',
    verificationStatus: 'placeholder',
    verificationNote: 'Replace with verified branch address, phone, and map URL',
  },
];

export const seedContact: ContactConfig = {
  whatsapp: '+233XXXXXXXXX',
  phone: '+233XXXXXXXXX',
  defaultMessage:
    "Hi Romedo Ventures, I'm interested in your products. Are they currently available?",
};

export const seedBusinessInfo: BusinessInfo = {};

export const seedStore: ContentStore = {
  products: seedProducts,
  categories: seedCategories,
  branches: seedBranches,
  contact: seedContact,
  businessInfo: seedBusinessInfo,
};
